import type { Metadata } from "next";
import { Inter, Roboto, Jacques_Francois_Shadow, Jacques_Francois } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import logo from "../public/logo.png";

const geistSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: "400",
});
const jacquesFrancoisShadow = Jacques_Francois_Shadow({
  variable: "--font-jacques-francois-shadow",
  subsets: ["latin"],
  weight: "400",
});

const jacquesFrancois = Jacques_Francois({
  variable: "--font-jacques-francois",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jacquesFrancoisShadow.variable} ${jacquesFrancois.variable} antialiased`}
      >
        {children}
        
      </body>
    </html>
  );
}
