import type { Metadata } from "next";
import {
  Inter,
  Roboto,
  Jacques_Francois_Shadow,
  Jacques_Francois,
} from "next/font/google";
import "./globals.css";

// Inter → variable font (supports variable)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Roboto → supports weights
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: "400",
});

// Jacques Francois Shadow → NO weight option
const jacquesFrancoisShadow = Jacques_Francois_Shadow({
  variable: "--font-jacques-francois-shadow",
  subsets: ["latin"],
  weight: "400",
});

// Jacques Francois → supports weight 400
const jacquesFrancois = Jacques_Francois({
  variable: "--font-jacques-francois",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${inter.variable}
          ${roboto.variable}
          ${jacquesFrancoisShadow.variable}
          ${jacquesFrancois.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
