import type { Metadata } from "next";
import { Geist, Geist_Mono, Jacques_Francois_Shadow, Jacques_Francois } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jacquesFrancoisShadow = Jacques_Francois_Shadow({
  variable: "--font-jacques-francois-shadow",
  subsets: ["latin"],
  weight: "400",
});

const jacquesFrancois = Jacques_Francois({
  variable: "--font-jacques-francois",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jacquesFrancoisShadow.variable} ${jacquesFrancois.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
